### ISSUE TITLE
Panic on backend

### ISSUE THREAD

**Issue by Slach** [Altinity/altinity-dashboard#116]
look details on https://github.com/Altinity/clickhouse-operator/issues/858

**Comment by ghjm** [comment]
I was not able to reproduce this, but I added some nil checks for k8s API return values in https://github.com/Altinity/altinity-dashboard/commit/be3c7e68f9ed0d62d6205fef0e564d6f1bd3c67d, which I hope should make it at least not panic.  @wangqinghuan please check if this fixes the issue for you.
