### ISSUE TITLE
Unauthorized when bindhost

### ISSUE THREAD

**Issue by wangqinghuan** [Altinity/altinity-dashboard#119]
1. ./adash-linux-x86_64  --openbrowser
  ![image](https://user-images.githubusercontent.com/22762150/148877430-f1ef84b1-6df1-4696-b1e3-40be50441469.png)
 2. ./adash-linux-x86_64  --openbrowser -bindhost 0.0.0.0
Unauthorized
![image](https://user-images.githubusercontent.com/22762150/148877369-1d574367-c97f-4777-8bac-d8350673bf9b.png)

**Comment by ghjm** [comment]
This is fixed by https://github.com/Altinity/altinity-dashboard/commit/16c216041a227d1b45ae4edd45dfa07d7c7b86f7.
