### ISSUE TITLE
Inform user if they are using an Older version of the clickhouse operator.

### ISSUE THREAD

**Issue by yctn** [Altinity/altinity-dashboard#93]
it would be nice to add a popup/notification to inform the user if they are using a operator version that is not the same as the latest one.

**Comment by ghjm** [comment]
Fixed by https://github.com/Altinity/altinity-dashboard/commit/2442ec24d6c2c94a51ea144917a15a338913b21b.

![image](https://user-images.githubusercontent.com/2052848/147025068-85c7f5b4-07b9-4128-ac70-54f3bde65a43.png)
